In [1]:
import zipfile
import os

# Specify the name of the uploaded zip file
uploaded_zip_file = 'Accelerometer.zip'

# Specify the directory where you want to extract the contents
extracted_dir = 'Accelerometer_CUA'

# Create the target directory if it doesn't exist
if not os.path.exists(extracted_dir):
    os.makedirs(extracted_dir)

# Open the uploaded zip file
zip_file_path = os.path.join(os.getcwd(), uploaded_zip_file)
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all the contents into the target directory
    zip_ref.extractall(extracted_dir)

print(f"Successfully extracted files to {extracted_dir}")

Successfully extracted files to Accelerometer_CUA


In [1]:
pip unistall pandas

Note: you may need to restart the kernel to use updated packages.


ERROR: unknown command "unistall" - maybe you meant "uninstall"



In [2]:
import zipfile
import os

# Specify the name of the uploaded zip file
uploaded_zip_file = 'Activity.zip'

# Specify the directory where you want to extract the contents
extracted_dir = 'Activity_CUA'

# Create the target directory if it doesn't exist
if not os.path.exists(extracted_dir):
    os.makedirs(extracted_dir)

# Open the uploaded zip file
zip_file_path = os.path.join(os.getcwd(), uploaded_zip_file)
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all the contents into the target directory
    zip_ref.extractall(extracted_dir)

print(f"Successfully extracted files to {extracted_dir}")

Successfully extracted files to Activity_CUA


In [3]:
import zipfile
import os

# Specify the name of the uploaded zip file
uploaded_zip_file = 'Gyroscope.zip'

# Specify the directory where you want to extract the contents
extracted_dir = 'Gyroscope_CUA'

# Create the target directory if it doesn't exist
if not os.path.exists(extracted_dir):
    os.makedirs(extracted_dir)

# Open the uploaded zip file
zip_file_path = os.path.join(os.getcwd(), uploaded_zip_file)
with zipfile.ZipFile(zip_file_path, 'r') as zip_ref:
    # Extract all the contents into the target directory
    zip_ref.extractall(extracted_dir)

print(f"Successfully extracted files to {extracted_dir}")

Successfully extracted files to Gyroscope_CUA


In [2]:
pip install pandas


DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


In [3]:
import os
import pandas as pd

# Specify the folder path
folder_path = 'Accelerometer_CUA/Accelerometer'

# Define column labels for Accelerometer data
accelerometer_labels = ['Systime', 'Event Time', 'ActivityID', 'X', 'Y', 'Z', 'Phone_orientation']

# Loop through each file in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)

        # Check if the file is empty before attempting to read
        if os.path.getsize(file_path) > 0:
            # Read the current CSV file
            current_df = pd.read_csv(file_path)

            # Label the columns according to the accelerometer description
            current_df.columns = accelerometer_labels

            # Save the DataFrame back to the same CSV file
            current_df.to_csv(file_path, index=False)
        else:
            print(f"Warning: Empty file - {file_name}")

print("Column labels updated for all CSV files in the folder.")

C:\Users\chiri\anaconda3\lib\site-packages\pandas\core\computation\expressions.py:21: UserWarning: Pandas requires version '2.8.0' or newer of 'numexpr' (version '2.7.3' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED
C:\Users\chiri\anaconda3\lib\site-packages\pandas\core\arrays\masked.py:62: UserWarning: Pandas requires version '1.3.4' or newer of 'bottleneck' (version '1.3.2' currently installed).
  from pandas.core import (


Column labels updated for all CSV files in the folder.


In [ ]:
pip install pandas


In [4]:
import os
import pandas as pd

# Specify the folder path
folder_path = 'Gyroscope_CUA/Gyroscope'

# Define column labels for Gyroscope data
gyroscope_labels = ['Systime', 'EventTime', 'ActivityID', 'X', 'Y', 'Z', 'Phone_orientation']

# Loop through each file in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)

        # Check if the file is empty before attempting to read
        if os.path.getsize(file_path) > 0:
            # Read the current CSV file
            current_df = pd.read_csv(file_path)

            # Label the columns according to the gyroscope description
            current_df.columns = gyroscope_labels

            # Save the DataFrame back to the same CSV file
            current_df.to_csv(file_path, index=False)
        else:
            print(f"Warning: Empty file - {file_name}")

print("Column labels updated for all CSV files in the folder.")


Column labels updated for all CSV files in the folder.


In [5]:
import os
import pandas as pd

# Specify the folder path
folder_path = 'Activity_CUA/Activity'

# Define column labels for Gyroscope data
gyroscope_labels = ['ID', 'SubjectID', 'Session_number', 'Start_time', 'End_time', 'Relative_Start_time', 'Relative_End_time','Gesture_scenario','TaskID','ContentID']

# Loop through each file in the folder
for file_name in os.listdir(folder_path):
    if file_name.endswith('.csv'):
        file_path = os.path.join(folder_path, file_name)

        # Check if the file is empty before attempting to read
        if os.path.getsize(file_path) > 0:
            # Read the current CSV file
            current_df = pd.read_csv(file_path)

            # Label the columns according to the gyroscope description
            current_df.columns = gyroscope_labels

            # Save the DataFrame back to the same CSV file
            current_df.to_csv(file_path, index=False)
        else:
            print(f"Warning: Empty file - {file_name}")

print("Column labels updated for all CSV files in the folder.")

Column labels updated for all CSV files in the folder.


In [7]:
import os
import pandas as pd

folder_path = 'Gyroscope_CUA/Gyroscope'
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]



# Ensure that the number of files to concatenate is not greater than the total available files
files_to_concatenate =  len(csv_files)

# Initialize an empty DataFrame to store the concatenated data
Gyroscope_df = pd.DataFrame()

# Iterate through the specified number of files and concatenate rows
for i in range(files_to_concatenate):
    file_path = os.path.join(folder_path, csv_files[i])
    df = pd.read_csv(file_path)

    # Ensure consistent columns
    if Gyroscope_df.empty:
        Gyroscope_df = df
    else:
        # Convert the set to a list
        common_columns = list(set(Gyroscope_df.columns) & set(df.columns))

# Now use this list for indexing
        Gyroscope_df = pd.concat([Gyroscope_df[common_columns], df[common_columns]], ignore_index=True)

# Display the concatenated DataFrame
Gyroscope_df.head()

Y  Phone_orientation      EventTime         Z         X  \
0  0.128893                  0  6785142573000 -1.016174  0.267864   
1 -0.536034                  0  6785152583000 -0.844521  0.215330   
2 -0.471893                  0  6785162593000  1.282512 -0.426079   
3  0.765720                  0  6785172602000 -0.275500 -0.072082   
4 -0.105680                  0  6785182673000 -0.409280 -0.034208   

        ActivityID        Systime  
0  100669011000001  1396226205573  
1  100669011000001  1396226205575  
2  100669011000001  1396226205577  
3  100669011000001  1396226205600  
4  100669011000001  1396226205604

In [8]:
import os
import pandas as pd

folder_path = 'Accelerometer_CUA/Accelerometer'
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]



# Ensure that the number of files to concatenate is not greater than the total available files
files_to_concatenate = len(csv_files)
# Initialize an empty DataFrame to store the concatenated data
A_concatenated_df = pd.DataFrame()

# Iterate through the specified number of files and concatenate rows
for i in range(files_to_concatenate):
    file_path = os.path.join(folder_path, csv_files[i])
    df = pd.read_csv(file_path)

    # Ensure consistent columns
    if A_concatenated_df.empty:
        A_concatenated_df = df
    else:
        
        # Convert the set to a list
        common_columns = list(set(A_concatenated_df.columns) & set(df.columns))

# Now use this list for indexing
        A_concatenated_df = pd.concat([A_concatenated_df[common_columns], df[common_columns]], ignore_index=True)# Keep only columns that are present in both DataFrames
        
# Display the concatenated DataFrame
A_concatenated_df.head()

Y  Phone_orientation         Z     Event Time         X  \
0  7.472902                  0  6.092046  6785142543000 -0.101754   
1  7.411850                  0  6.323685  6785152552000 -0.121506   
2  7.313688                  0  6.293758  6785162562000 -0.126893   
3  7.307702                  0  6.186019  6785172572000 -0.083797   
4  7.389704                  0  6.066308  6785182643000 -0.003591   

        ActivityID        Systime  
0  100669011000001  1396226205572  
1  100669011000001  1396226205574  
2  100669011000001  1396226205576  
3  100669011000001  1396226205598  
4  100669011000001  1396226205601

In [9]:

import os
import pandas as pd

folder_path = 'Activity_CUA/Activity'
csv_files = [file for file in os.listdir(folder_path) if file.endswith('.csv')]



# Ensure that the number of files to concatenate is not greater than the total available files
files_to_concatenate =  len(csv_files)

# Initialize an empty DataFrame to store the concatenated data
Act_concatenated_df = pd.DataFrame()

# Iterate through the specified number of files and concatenate rows
for i in range(files_to_concatenate):
    file_path = os.path.join(folder_path, csv_files[i])
    df = pd.read_csv(file_path)

    # Ensure consistent columns
    if Act_concatenated_df.empty:
        Act_concatenated_df = df
    else:
        # Keep only columns that are present in both DataFrames
        # Convert the set to a list
        common_columns = list(set(Act_concatenated_df.columns) & set(df.columns))

# Now use this list for indexing
        Act_concatenated_df = pd.concat([Act_concatenated_df[common_columns], df[common_columns]], ignore_index=True)
        
# Display the concatenated DataFrame
Act_concatenated_df.head()

SubjectID  TaskID       End_time     Start_time  Session_number  ContentID  \
0     100669       7  1396226578198  1396226421894               1          2   
1     100669       7  1396226650781  1396226600720               1          2   
2     100669       7  1396226653876  1396226600720               1          2   
3     100669       7  1396226737648  1396226672419               1          2   
4     100669       7  1396226937462  1396226745978               1          3   

                ID  Relative_End_time  Gesture_scenario  Relative_Start_time  
0  100669012000001            7157788                 1              7001484  
1  100669012000002            7230371                 1              7180310  
2  100669012000002            7233466                 1              7180310  
3  100669012000003            7317238                 1              7252008  
4  100669013000001            7517052                 1              7325568

In [10]:
print(Act_concatenated_df)

     SubjectID  TaskID       End_time     Start_time  Session_number  \
0       100669       7  1396226578198  1396226421894               1   
1       100669       7  1396226650781  1396226600720               1   
2       100669       7  1396226653876  1396226600720               1   
3       100669       7  1396226737648  1396226672419               1   
4       100669       7  1396226937462  1396226745978               1   
..         ...     ...            ...            ...             ...   
117     186676       7  1399075996157  1399075988761               5   
118     186676       7  1399076004460  1399076000278               5   
119     186676       7  1399076017448  1399076014044               5   
120     186676       3  1399158518576  1399158333135               6   
121     186676       3  1399158883323  1399158518621               6   

     ContentID               ID  Relative_End_time  Gesture_scenario  \
0            2  100669012000001            7157788             

In [11]:
print(A_concatenated_df)

                Y  Phone_orientation         Z     Event Time         X  \
0        7.472902                  0  6.092046  6785142543000 -0.101754   
1        7.411850                  0  6.323685  6785152552000 -0.121506   
2        7.313688                  0  6.293758  6785162562000 -0.126893   
3        7.307702                  0  6.186019  6785172572000 -0.083797   
4        7.389704                  0  6.066308  6785182643000 -0.003591   
...           ...                ...       ...            ...       ...   
1763585  8.057087                  0  5.989694   847019860000 -2.065597   
1763586  8.067862                  0  5.854422   847030542000 -2.062006   
1763587  8.082227                  0  5.513248   847041986000 -2.127248   
1763588  8.135497                  0  5.259462   847054193000 -2.097321   
1763589  8.185776                  0  5.042788   847059014000 -2.085948   

              ActivityID        Systime  
0        100669011000001  1396226205572  
1        100669

In [12]:
print(Gyroscope_df)

                Y  Phone_orientation      EventTime         Z         X  \
0        0.128893                  0  6785142573000 -1.016174  0.267864   
1       -0.536034                  0  6785152583000 -0.844521  0.215330   
2       -0.471893                  0  6785162593000  1.282512 -0.426079   
3        0.765720                  0  6785172602000 -0.275500 -0.072082   
4       -0.105680                  0  6785182673000 -0.409280 -0.034208   
...           ...                ...            ...       ...       ...   
1763333 -0.228158                  0   847019891000 -0.027184 -0.050091   
1763334 -0.153327                  0   847030572000 -0.021991 -0.017410   
1763335 -0.099266                  0   847042016000 -0.018631  0.046731   
1763336 -0.032070                  0   847054193000 -0.014966  0.107512   
1763337  0.031154                  0   847059014000 -0.007636  0.132863   

              ActivityID        Systime  
0        100669011000001  1396226205573  
1        100669

In [13]:
# Assuming 'df' is your DataFrame
Gyroscope_df['ID'] =Gyroscope_df['ActivityID'].astype(str).str[:6]

In [14]:
print(A_concatenated_df)

                Y  Phone_orientation         Z     Event Time         X  \
0        7.472902                  0  6.092046  6785142543000 -0.101754   
1        7.411850                  0  6.323685  6785152552000 -0.121506   
2        7.313688                  0  6.293758  6785162562000 -0.126893   
3        7.307702                  0  6.186019  6785172572000 -0.083797   
4        7.389704                  0  6.066308  6785182643000 -0.003591   
...           ...                ...       ...            ...       ...   
1763585  8.057087                  0  5.989694   847019860000 -2.065597   
1763586  8.067862                  0  5.854422   847030542000 -2.062006   
1763587  8.082227                  0  5.513248   847041986000 -2.127248   
1763588  8.135497                  0  5.259462   847054193000 -2.097321   
1763589  8.185776                  0  5.042788   847059014000 -2.085948   

              ActivityID        Systime  
0        100669011000001  1396226205572  
1        100669

In [15]:

# Assuming 'df' is your DataFrame
A_concatenated_df['ID'] =A_concatenated_df['ActivityID'].astype(str).str[:6]


In [16]:
print(Gyroscope_df)

                Y  Phone_orientation      EventTime         Z         X  \
0        0.128893                  0  6785142573000 -1.016174  0.267864   
1       -0.536034                  0  6785152583000 -0.844521  0.215330   
2       -0.471893                  0  6785162593000  1.282512 -0.426079   
3        0.765720                  0  6785172602000 -0.275500 -0.072082   
4       -0.105680                  0  6785182673000 -0.409280 -0.034208   
...           ...                ...            ...       ...       ...   
1763333 -0.228158                  0   847019891000 -0.027184 -0.050091   
1763334 -0.153327                  0   847030572000 -0.021991 -0.017410   
1763335 -0.099266                  0   847042016000 -0.018631  0.046731   
1763336 -0.032070                  0   847054193000 -0.014966  0.107512   
1763337  0.031154                  0   847059014000 -0.007636  0.132863   

              ActivityID        Systime      ID  
0        100669011000001  1396226205573  100669  

In [17]:




Gyroscope_df.drop(['Systime', 'EventTime', 'ActivityID'], axis=1, inplace=True)


In [18]:
print(Gyroscope_df)

                Y  Phone_orientation         Z         X      ID
0        0.128893                  0 -1.016174  0.267864  100669
1       -0.536034                  0 -0.844521  0.215330  100669
2       -0.471893                  0  1.282512 -0.426079  100669
3        0.765720                  0 -0.275500 -0.072082  100669
4       -0.105680                  0 -0.409280 -0.034208  100669
...           ...                ...       ...       ...     ...
1763333 -0.228158                  0 -0.027184 -0.050091  186676
1763334 -0.153327                  0 -0.021991 -0.017410  186676
1763335 -0.099266                  0 -0.018631  0.046731  186676
1763336 -0.032070                  0 -0.014966  0.107512  186676
1763337  0.031154                  0 -0.007636  0.132863  186676

[1763338 rows x 5 columns]


In [19]:

A_concatenated_df.drop(['Systime', 'Event Time'], axis=1, inplace=True)

# GYROSCOPE X,Y

In [20]:
import pandas as pd
import numpy as np

# Feature extraction functions as defined earlier
def extract_ferret_measure(data):
    x_values, y_values = data['X'], data['Y']
    x_ferret = np.max(x_values) - np.min(x_values)
    y_ferret = np.max(y_values) - np.min(y_values)
    F = x_ferret / y_ferret if y_ferret != 0 else np.nan
    return F

def extract_centroid_distance(data):
    x_values, y_values = data['X'], data['Y']
    centroid_x = np.mean(x_values)
    centroid_y = np.mean(y_values)
    distances = np.sqrt((np.array(x_values) - centroid_x) ** 2 + (np.array(y_values) - centroid_y) ** 2)
    centroid_distance = np.mean(distances)
    return centroid_distance

def extract_polygon_area(data):
    x_values, y_values = data['X'], data['Y']
    area = 0.5 * np.abs(np.dot(x_values, np.roll(y_values, 1)) - np.dot(y_values, np.roll(x_values, 1)))
    return area

def extract_polygon_perimeter(data):
    x_values, y_values = data['X'], data['Y']
    dx = np.diff(x_values)
    dy = np.diff(y_values)
    perimeter = np.sum(np.sqrt(dx**2 + dy**2))
    return perimeter


# Function to process data in windows of 100 rows and include 'ID'
def process_data_in_windows(df, window_size=100):
    windowed_features = []

    for start in range(0, len(df), window_size):
        end = start + window_size
        window_data = df.iloc[start:end]

        if len(window_data) < window_size:
            continue  # Skip incomplete windows

        # Extracting features
        ferret_measure = extract_ferret_measure(window_data)
        centroid_distance = extract_centroid_distance(window_data)
        polygon_area = extract_polygon_area(window_data)
        polygon_perimeter = extract_polygon_perimeter(window_data)

        # Get the 'ID' from the first row in the window
        window_id = window_data.iloc[0]['ID']

        windowed_features.append([window_id, ferret_measure, centroid_distance, polygon_area, polygon_perimeter])

    return pd.DataFrame(windowed_features, columns=['ID', 'Ferret Measure(gyroxy)', 'Centroid Distance(gyroxy)', 'Polygon Area(gyroxy)', 'Polygon Perimeter(gyroxy)'])

# Replace 'Gyroscope_df' with your actual DataFrame variable
gyroxy_features = process_data_in_windows(Gyroscope_df)

print(gyroxy_features)



           ID  Ferret Measure(gyroxy)  Centroid Distance(gyroxy)  \
0      100669                0.616612                   0.157566   
1      100669                1.580424                   0.178812   
2      100669                0.950282                   0.150707   
3      100669                0.903312                   0.386830   
4      100669                0.570392                   0.240423   
...       ...                     ...                        ...   
17628  186676                1.003663                   0.126849   
17629  186676                0.796665                   0.152636   
17630  186676                0.463958                   0.137867   
17631  186676                0.441687                   0.231708   
17632  186676                0.597854                   0.112320   

       Polygon Area(gyroxy)  Polygon Perimeter(gyroxy)  
0                  0.423369                   6.120407  
1                  0.004262                   4.980247  
2           

# GYROSCOPE Y,Z

In [21]:
import pandas as pd
import numpy as np

# Feature extraction functions as defined earlier
def extract_ferret_measure(data):
    y_values, z_values = data['Y'], data['Z']
    y_ferret = np.max(y_values) - np.min(y_values)
    z_ferret = np.max(z_values) - np.min(z_values)
    F = y_ferret / z_ferret if z_ferret != 0 else np.nan
    return F

def extract_centroid_distance(data):
    y_values, z_values = data['Y'], data['Z']
    centroid_y = np.mean(y_values)
    centroid_z = np.mean(z_values)
    distances = np.sqrt((np.array(y_values) - centroid_y) ** 2 + (np.array(z_values) - centroid_z) ** 2)
    centroid_distance = np.mean(distances)
    return centroid_distance

def extract_polygon_area(data):
    y_values, z_values = data['Y'], data['Z']
    area = 0.5 * np.abs(np.dot(y_values, np.roll(z_values, 1)) - np.dot(z_values, np.roll(y_values, 1)))
    return area

def extract_polygon_perimeter(data):
    y_values, z_values = data['Y'], data['Z']
    dy = np.diff(y_values)
    dz = np.diff(z_values)
    perimeter = np.sum(np.sqrt(dy**2 + dz**2))
    return perimeter


# Function to process data in windows of 100 rows and include 'ID'
def process_data_in_windows(df, window_size=100):
    windowed_features = []

    for start in range(0, len(df), window_size):
        end = start + window_size
        window_data = df.iloc[start:end]

        if len(window_data) < window_size:
            continue  # Skip incomplete windows

        # Extracting features
        ferret_measure = extract_ferret_measure(window_data)
        centroid_distance = extract_centroid_distance(window_data)
        polygon_area = extract_polygon_area(window_data)
        polygon_perimeter = extract_polygon_perimeter(window_data)

        # Get the 'ID' from the first row in the window
        window_id = window_data.iloc[0]['ID']

        windowed_features.append([window_id, ferret_measure, centroid_distance, polygon_area, polygon_perimeter])

    return pd.DataFrame(windowed_features, columns=['ID', 'Ferret Measure(gyroyz)', 'Centroid Distance(gyroyz)', 'Polygon Area(gyroyz)', 'Polygon Perimeter(gyroyz)'])

# Replace 'Gyroscope_df' with your actual DataFrame variable
gyroyz_features = process_data_in_windows(Gyroscope_df)

print(gyroyz_features)

           ID  Ferret Measure(gyroyz)  Centroid Distance(gyroyz)  \
0      100669                0.566303                   0.179661   
1      100669                1.242532                   0.133076   
2      100669                1.998975                   0.106603   
3      100669                0.420213                   1.632013   
4      100669                3.081395                   0.230317   
...       ...                     ...                        ...   
17628  186676                2.667752                   0.103266   
17629  186676                2.685323                   0.119757   
17630  186676                2.854115                   0.138280   
17631  186676                0.781973                   0.330728   
17632  186676                5.150000                   0.095842   

       Polygon Area(gyroyz)  Polygon Perimeter(gyroyz)  
0                  1.491053                   8.126881  
1                  0.003931                   3.977403  
2           

# GYROSCOPE Z,X

In [22]:
import pandas as pd
import numpy as np

# Feature extraction functions as defined earlier
def extract_ferret_measure(data):
    z_values, x_values = data['Z'], data['X']
    z_ferret = np.max(z_values) - np.min(z_values)
    x_ferret = np.max(x_values) - np.min(x_values)
    F = z_ferret / x_ferret if x_ferret != 0 else np.nan
    return F

def extract_centroid_distance(data):
    z_values, x_values = data['Z'], data['X']
    centroid_z = np.mean(z_values)
    centroid_x = np.mean(x_values)
    distances = np.sqrt((np.array(z_values) - centroid_z) ** 2 + (np.array(x_values) - centroid_x) ** 2)
    centroid_distance = np.mean(distances)
    return centroid_distance

def extract_polygon_area(data):
    z_values, x_values = data['Z'], data['X']
    area = 0.5 * np.abs(np.dot(z_values, np.roll(x_values, 1)) - np.dot(x_values, np.roll(z_values, 1)))
    return area

def extract_polygon_perimeter(data):
    z_values, x_values = data['Z'], data['X']
    dz = np.diff(z_values)
    dx = np.diff(x_values)
    perimeter = np.sum(np.sqrt(dz**2 + dx**2))
    return perimeter


# Function to process data in windows of 100 rows and include 'ID'
def process_data_in_windows(df, window_size=100):
    windowed_features = []

    for start in range(0, len(df), window_size):
        end = start + window_size
        window_data = df.iloc[start:end]

        if len(window_data) < window_size:
            continue  # Skip incomplete windows

        # Extracting features
        ferret_measure = extract_ferret_measure(window_data)
        centroid_distance = extract_centroid_distance(window_data)
        polygon_area = extract_polygon_area(window_data)
        polygon_perimeter = extract_polygon_perimeter(window_data)

        # Get the 'ID' from the first row in the window
        window_id = window_data.iloc[0]['ID']

        windowed_features.append([window_id, ferret_measure, centroid_distance, polygon_area, polygon_perimeter])

    return pd.DataFrame(windowed_features, columns=['ID', 'Ferret Measure(gyrozx)', 'Centroid Distance(gyrozx)', 'Polygon Area(gyrozx)', 'Polygon Perimeter(gyrozx)'])

# Replace 'Gyroscope_df' with your actual DataFrame variable
gyrozx_features = process_data_in_windows(Gyroscope_df)

print(gyrozx_features)

           ID  Ferret Measure(gyrozx)  Centroid Distance(gyrozx)  \
0      100669                2.863775                   0.188755   
1      100669                0.509236                   0.180096   
2      100669                0.526429                   0.135639   
3      100669                2.634466                   1.646785   
4      100669                0.568957                   0.125642   
...       ...                     ...                        ...   
17628  186676                0.373479                   0.084747   
17629  186676                0.467442                   0.105985   
17630  186676                0.755179                   0.083622   
17631  186676                2.895304                   0.236960   
17632  186676                0.324786                   0.060704   

       Polygon Area(gyrozx)  Polygon Perimeter(gyrozx)  
0                  0.021297                   6.197423  
1                  0.143342                   3.590862  
2           

# ACCELEROMETER X,Y

In [23]:
# Print column names of A_concatenated_df
print(A_concatenated_df.columns)


Index(['Y', 'Phone_orientation', 'Z', 'X', 'ActivityID', 'ID'], dtype='object')


In [24]:
A_concatenated_df.drop(['ActivityID'], axis=1, inplace=True)

In [25]:
print(A_concatenated_df.columns)

Index(['Y', 'Phone_orientation', 'Z', 'X', 'ID'], dtype='object')


In [26]:
import pandas as pd
import numpy as np

# Feature extraction functions as defined earlier
def extract_ferret_measure(data):
    x_values, y_values = data['X'], data['Y']
    x_ferret = np.max(x_values) - np.min(x_values)
    y_ferret = np.max(y_values) - np.min(y_values)
    F = x_ferret / y_ferret if y_ferret != 0 else np.nan
    return F

def extract_centroid_distance(data):
    x_values, y_values = data['X'], data['Y']
    centroid_x = np.mean(x_values)
    centroid_y = np.mean(y_values)
    distances = np.sqrt((np.array(x_values) - centroid_x) ** 2 + (np.array(y_values) - centroid_y) ** 2)
    centroid_distance = np.mean(distances)
    return centroid_distance

def extract_polygon_area(data):
    x_values, y_values = data['X'], data['Y']
    area = 0.5 * np.abs(np.dot(x_values, np.roll(y_values, 1)) - np.dot(y_values, np.roll(x_values, 1)))
    return area

def extract_polygon_perimeter(data):
    x_values, y_values = data['X'], data['Y']
    dx = np.diff(x_values)
    dy = np.diff(y_values)
    perimeter = np.sum(np.sqrt(dx**2 + dy**2))
    return perimeter


# Function to process data in windows of 100 rows and include 'ID'
def process_data_in_windows(df, window_size=100):
    windowed_features = []

    for start in range(0, len(df), window_size):
        end = start + window_size
        window_data = df.iloc[start:end]

        if len(window_data) < window_size:
            continue  # Skip incomplete windows

        # Extracting features
        ferret_measure = extract_ferret_measure(window_data)
        centroid_distance = extract_centroid_distance(window_data)
        polygon_area = extract_polygon_area(window_data)
        polygon_perimeter = extract_polygon_perimeter(window_data)

        # Get the 'ID' from the first row in the window
        window_id = window_data.iloc[0]['ID']

        windowed_features.append([window_id, ferret_measure, centroid_distance, polygon_area, polygon_perimeter])

    return pd.DataFrame(windowed_features, columns=['ID', 'Ferret Measure(accxy)', 'Centroid Distance(accxy)', 'Polygon Area(accxy)', 'Polygon Perimeter(accxy)'])

# Replace 'Gyroscope_df' with your actual DataFrame variable
acceleroxy_features = process_data_in_windows(A_concatenated_df)

print(acceleroxy_features)



           ID  Ferret Measure(accxy)  Centroid Distance(accxy)  \
0      100669               0.653896                  0.307439   
1      100669               1.046059                  0.356021   
2      100669               1.561073                  0.288214   
3      100669               0.985135                  4.509599   
4      100669               1.534549                  0.371832   
...       ...                    ...                       ...   
17630  186676               1.094025                  0.142493   
17631  186676               0.869119                  0.146733   
17632  186676               0.942703                  0.115567   
17633  186676               4.717417                  0.791349   
17634  186676               2.830576                  0.201599   

       Polygon Area(accxy)  Polygon Perimeter(accxy)  
0                 0.126997                 10.049717  
1                 0.396814                 11.305019  
2                 0.019777                

# ACCELEROMETER Y,Z

In [27]:
import pandas as pd
import numpy as np

# Feature extraction functions as defined earlier
def extract_ferret_measure(data):
    y_values, z_values = data['Y'], data['Z']
    y_ferret = np.max(y_values) - np.min(y_values)
    z_ferret = np.max(z_values) - np.min(z_values)
    F = y_ferret / z_ferret if z_ferret != 0 else np.nan
    return F

def extract_centroid_distance(data):
    y_values, z_values = data['Y'], data['Z']
    centroid_y = np.mean(y_values)
    centroid_z = np.mean(z_values)
    distances = np.sqrt((np.array(y_values) - centroid_y) ** 2 + (np.array(z_values) - centroid_z) ** 2)
    centroid_distance = np.mean(distances)
    return centroid_distance

def extract_polygon_area(data):
    y_values, z_values = data['Y'], data['Z']
    area = 0.5 * np.abs(np.dot(y_values, np.roll(z_values, 1)) - np.dot(z_values, np.roll(y_values, 1)))
    return area

def extract_polygon_perimeter(data):
    y_values, z_values = data['Y'], data['Z']
    dy = np.diff(y_values)
    dz = np.diff(z_values)
    perimeter = np.sum(np.sqrt(dy**2 + dz**2))
    return perimeter


# Function to process data in windows of 100 rows and include 'ID'
def process_data_in_windows(df, window_size=100):
    windowed_features = []

    for start in range(0, len(df), window_size):
        end = start + window_size
        window_data = df.iloc[start:end]

        if len(window_data) < window_size:
            continue  # Skip incomplete windows

        # Extracting features
        ferret_measure = extract_ferret_measure(window_data)
        centroid_distance = extract_centroid_distance(window_data)
        polygon_area = extract_polygon_area(window_data)
        polygon_perimeter = extract_polygon_perimeter(window_data)

        # Get the 'ID' from the first row in the window
        window_id = window_data.iloc[0]['ID']

        windowed_features.append([window_id, ferret_measure, centroid_distance, polygon_area, polygon_perimeter])

    return pd.DataFrame(windowed_features, columns=['ID', 'Ferret Measure(accyz)', 'Centroid Distance(accyz)', 'Polygon Area(accyz)', 'Polygon Perimeter(accyz)'])

# Replace 'Gyroscope_df' with your actual DataFrame variable
acceleroyz_features = process_data_in_windows(A_concatenated_df)

print(acceleroyz_features)

           ID  Ferret Measure(accyz)  Centroid Distance(accyz)  \
0      100669               0.740989                  0.399202   
1      100669               0.297710                  0.674483   
2      100669               0.253358                  0.451814   
3      100669               1.414049                  3.522641   
4      100669               0.408537                  0.625104   
...       ...                    ...                       ...   
17630  186676               0.356121                  0.340417   
17631  186676               0.335727                  0.319892   
17632  186676               0.422626                  0.227916   
17633  186676               0.677952                  0.352900   
17634  186676               0.151661                  0.241693   

       Polygon Area(accyz)  Polygon Perimeter(accyz)  
0                 0.471914                 12.862190  
1                 0.833709                 20.952302  
2                 0.083674                

# ACCELEROMETER Z,X

In [28]:

import pandas as pd
import numpy as np

# Feature extraction functions as defined earlier
def extract_ferret_measure(data):
    z_values, x_values = data['Z'], data['X']
    z_ferret = np.max(z_values) - np.min(z_values)
    x_ferret = np.max(x_values) - np.min(x_values)
    F = z_ferret / x_ferret if x_ferret != 0 else np.nan
    return F

def extract_centroid_distance(data):
    z_values, x_values = data['Z'], data['X']
    centroid_z = np.mean(z_values)
    centroid_x = np.mean(x_values)
    distances = np.sqrt((np.array(z_values) - centroid_z) ** 2 + (np.array(x_values) - centroid_x) ** 2)
    centroid_distance = np.mean(distances)
    return centroid_distance

def extract_polygon_area(data):
    z_values, x_values = data['Z'], data['X']
    area = 0.5 * np.abs(np.dot(z_values, np.roll(x_values, 1)) - np.dot(x_values, np.roll(z_values, 1)))
    return area

def extract_polygon_perimeter(data):
    z_values, x_values = data['Z'], data['X']
    dz = np.diff(z_values)
    dx = np.diff(x_values)
    perimeter = np.sum(np.sqrt(dz**2 + dx**2))
    return perimeter


# Function to process data in windows of 100 rows and include 'ID'
def process_data_in_windows(df, window_size=100):
    windowed_features = []

    for start in range(0, len(df), window_size):
        end = start + window_size
        window_data = df.iloc[start:end]

        if len(window_data) < window_size:
            continue  # Skip incomplete windows

        # Extracting features
        ferret_measure = extract_ferret_measure(window_data)
        centroid_distance = extract_centroid_distance(window_data)
        polygon_area = extract_polygon_area(window_data)
        polygon_perimeter = extract_polygon_perimeter(window_data)

        # Get the 'ID' from the first row in the window
        window_id = window_data.iloc[0]['ID']

        windowed_features.append([window_id, ferret_measure, centroid_distance, polygon_area, polygon_perimeter])

    return pd.DataFrame(windowed_features, columns=['ID', 'Ferret Measure(acczx)', 'Centroid Distance(acczx)', 'Polygon Area(acczx)', 'Polygon Perimeter(acczx)'])

# Replace 'Gyroscope_df' with your actual DataFrame variable
accelerozx_features = process_data_in_windows(Gyroscope_df)

print(accelerozx_features)

           ID  Ferret Measure(acczx)  Centroid Distance(acczx)  \
0      100669               2.863775                  0.188755   
1      100669               0.509236                  0.180096   
2      100669               0.526429                  0.135639   
3      100669               2.634466                  1.646785   
4      100669               0.568957                  0.125642   
...       ...                    ...                       ...   
17628  186676               0.373479                  0.084747   
17629  186676               0.467442                  0.105985   
17630  186676               0.755179                  0.083622   
17631  186676               2.895304                  0.236960   
17632  186676               0.324786                  0.060704   

       Polygon Area(acczx)  Polygon Perimeter(acczx)  
0                 0.021297                  6.197423  
1                 0.143342                  3.590862  
2                 0.012133                

In [29]:
print(acceleroyz_features)

           ID  Ferret Measure(accyz)  Centroid Distance(accyz)  \
0      100669               0.740989                  0.399202   
1      100669               0.297710                  0.674483   
2      100669               0.253358                  0.451814   
3      100669               1.414049                  3.522641   
4      100669               0.408537                  0.625104   
...       ...                    ...                       ...   
17630  186676               0.356121                  0.340417   
17631  186676               0.335727                  0.319892   
17632  186676               0.422626                  0.227916   
17633  186676               0.677952                  0.352900   
17634  186676               0.151661                  0.241693   

       Polygon Area(accyz)  Polygon Perimeter(accyz)  
0                 0.471914                 12.862190  
1                 0.833709                 20.952302  
2                 0.083674                

In [30]:
acceleroxy_features = acceleroxy_features[:-2]

In [31]:
print(acceleroxy_features)

           ID  Ferret Measure(accxy)  Centroid Distance(accxy)  \
0      100669               0.653896                  0.307439   
1      100669               1.046059                  0.356021   
2      100669               1.561073                  0.288214   
3      100669               0.985135                  4.509599   
4      100669               1.534549                  0.371832   
...       ...                    ...                       ...   
17628  186676               1.183922                  0.158304   
17629  186676               0.973371                  0.154844   
17630  186676               1.094025                  0.142493   
17631  186676               0.869119                  0.146733   
17632  186676               0.942703                  0.115567   

       Polygon Area(accxy)  Polygon Perimeter(accxy)  
0                 0.126997                 10.049717  
1                 0.396814                 11.305019  
2                 0.019777                

In [32]:
from sklearn.preprocessing import MinMaxScaler

def normalize_dataframe_excluding_id(df, id_column):
    # Create a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()

    # Extract the ID column and store it separately
    id_col = df_copy[id_column]

    # Columns to be normalized (excluding the ID column)
    columns_to_normalize = [col for col in df_copy.columns if col != id_column]

    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize the data
    df_copy[columns_to_normalize] = scaler.fit_transform(df_copy[columns_to_normalize])

    # Replace the ID column with its original values
    df_copy[id_column] = id_col

    return df_copy

# Normalize the DataFrame excluding 'ID'
normalized_acceleroxy = normalize_dataframe_excluding_id(acceleroxy_features, 'ID')

print(normalized_acceleroxy)


           ID  Ferret Measure(accxy)  Centroid Distance(accxy)  \
0      100669               0.053376                  0.061894   
1      100669               0.101684                  0.072494   
2      100669               0.165124                  0.057699   
3      100669               0.094179                  0.978768   
4      100669               0.161857                  0.075943   
...       ...                    ...                       ...   
17628  186676               0.118666                  0.029354   
17629  186676               0.092730                  0.028599   
17630  186676               0.107592                  0.025904   
17631  186676               0.079888                  0.026829   
17632  186676               0.088952                  0.020029   

       Polygon Area(accxy)  Polygon Perimeter(accxy)  
0                 0.002688                  0.075813  
1                 0.008400                  0.087172  
2                 0.000419                

In [33]:
from sklearn.preprocessing import MinMaxScaler

def normalize_dataframe_excluding_id(df, id_column):
    # Create a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()

    # Extract the ID column and store it separately
    id_col = df_copy[id_column]

    # Columns to be normalized (excluding the ID column)
    columns_to_normalize = [col for col in df_copy.columns if col != id_column]

    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize the data
    df_copy[columns_to_normalize] = scaler.fit_transform(df_copy[columns_to_normalize])

    # Replace the ID column with its original values
    df_copy[id_column] = id_col

    return df_copy

# Normalize the DataFrame excluding 'ID'
normalized_acceleroyz = normalize_dataframe_excluding_id(acceleroyz_features, 'ID')

print(normalized_acceleroyz)


           ID  Ferret Measure(accyz)  Centroid Distance(accyz)  \
0      100669               0.275119                  0.093037   
1      100669               0.093330                  0.161819   
2      100669               0.075142                  0.106183   
3      100669               0.551141                  0.873459   
4      100669               0.138780                  0.149481   
...       ...                    ...                       ...   
17630  186676               0.117285                  0.078349   
17631  186676               0.108921                  0.073221   
17632  186676               0.144558                  0.050240   
17633  186676               0.249268                  0.081468   
17634  186676               0.033435                  0.053682   

       Polygon Area(accyz)  Polygon Perimeter(accyz)  
0                 0.008967                  0.081195  
1                 0.015841                  0.141317  
2                 0.001590                

In [34]:
from sklearn.preprocessing import MinMaxScaler

def normalize_dataframe_excluding_id(df, id_column):
    # Create a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()

    # Extract the ID column and store it separately
    id_col = df_copy[id_column]

    # Columns to be normalized (excluding the ID column)
    columns_to_normalize = [col for col in df_copy.columns if col != id_column]

    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize the data
    df_copy[columns_to_normalize] = scaler.fit_transform(df_copy[columns_to_normalize])

    # Replace the ID column with its original values
    df_copy[id_column] = id_col

    return df_copy

# Normalize the DataFrame excluding 'ID'
normalized_accelerozx = normalize_dataframe_excluding_id(accelerozx_features, 'ID')

print(normalized_accelerozx)


           ID  Ferret Measure(acczx)  Centroid Distance(acczx)  \
0      100669               0.374142                  0.104882   
1      100669               0.058186                  0.099886   
2      100669               0.060493                  0.074236   
3      100669               0.343371                  0.946111   
4      100669               0.066200                  0.068469   
...       ...                    ...                       ...   
17628  186676               0.039969                  0.044873   
17629  186676               0.052578                  0.057127   
17630  186676               0.091189                  0.044224   
17631  186676               0.378373                  0.132694   
17632  186676               0.033435                  0.031001   

       Polygon Area(acczx)  Polygon Perimeter(acczx)  
0                 0.003716                  0.138271  
1                 0.025011                  0.075452  
2                 0.002117                

In [35]:
from sklearn.preprocessing import MinMaxScaler

def normalize_dataframe_excluding_id(df, id_column):
    # Create a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()

    # Extract the ID column and store it separately
    id_col = df_copy[id_column]

    # Columns to be normalized (excluding the ID column)
    columns_to_normalize = [col for col in df_copy.columns if col != id_column]

    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize the data
    df_copy[columns_to_normalize] = scaler.fit_transform(df_copy[columns_to_normalize])

    # Replace the ID column with its original values
    df_copy[id_column] = id_col

    return df_copy

# Normalize the DataFrame excluding 'ID'
normalized_gyroxy = normalize_dataframe_excluding_id(gyroxy_features, 'ID')

print(normalized_gyroxy)


           ID  Ferret Measure(gyroxy)  Centroid Distance(gyroxy)  \
0      100669                0.080112                   0.097613   
1      100669                0.240486                   0.111414   
2      100669                0.135633                   0.093157   
3      100669                0.127818                   0.246544   
4      100669                0.072421                   0.151437   
...       ...                     ...                        ...   
17628  186676                0.144516                   0.077659   
17629  186676                0.110072                   0.094410   
17630  186676                0.054711                   0.084816   
17631  186676                0.051005                   0.145776   
17632  186676                0.076991                   0.068220   

       Polygon Area(gyroxy)  Polygon Perimeter(gyroxy)  
0                  0.039899                   0.115210  
1                  0.000402                   0.091714  
2           

In [36]:
from sklearn.preprocessing import MinMaxScaler

def normalize_dataframe_excluding_id(df, id_column):
    # Create a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()

    # Extract the ID column and store it separately
    id_col = df_copy[id_column]

    # Columns to be normalized (excluding the ID column)
    columns_to_normalize = [col for col in df_copy.columns if col != id_column]

    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize the data
    df_copy[columns_to_normalize] = scaler.fit_transform(df_copy[columns_to_normalize])

    # Replace the ID column with its original values
    df_copy[id_column] = id_col

    return df_copy

# Normalize the DataFrame excluding 'ID'
normalized_gyroyz = normalize_dataframe_excluding_id(gyroyz_features, 'ID')

print(normalized_gyroyz)


           ID  Ferret Measure(gyroyz)  Centroid Distance(gyroyz)  \
0      100669                0.034273                   0.095521   
1      100669                0.085346                   0.069850   
2      100669                0.142477                   0.055262   
3      100669                0.023239                   0.895854   
4      100669                0.224228                   0.123435   
...       ...                     ...                        ...   
17628  186676                0.192988                   0.053423   
17629  186676                0.194315                   0.062510   
17630  186676                0.207063                   0.072718   
17631  186676                0.050562                   0.178768   
17632  186676                0.380462                   0.049332   

       Polygon Area(gyroyz)  Polygon Perimeter(gyroyz)  
0                  0.124569                   0.222375  
1                  0.000328                   0.102574  
2           

In [37]:
from sklearn.preprocessing import MinMaxScaler

def normalize_dataframe_excluding_id(df, id_column):
    # Create a copy of the dataframe to avoid modifying the original
    df_copy = df.copy()

    # Extract the ID column and store it separately
    id_col = df_copy[id_column]

    # Columns to be normalized (excluding the ID column)
    columns_to_normalize = [col for col in df_copy.columns if col != id_column]

    # Initialize the MinMaxScaler
    scaler = MinMaxScaler()

    # Normalize the data
    df_copy[columns_to_normalize] = scaler.fit_transform(df_copy[columns_to_normalize])

    # Replace the ID column with its original values
    df_copy[id_column] = id_col

    return df_copy

# Normalize the DataFrame excluding 'ID'
normalized_gyrozx = normalize_dataframe_excluding_id(gyrozx_features, 'ID')

print(normalized_gyrozx)


           ID  Ferret Measure(gyrozx)  Centroid Distance(gyrozx)  \
0      100669                0.374142                   0.104882   
1      100669                0.058186                   0.099886   
2      100669                0.060493                   0.074236   
3      100669                0.343371                   0.946111   
4      100669                0.066200                   0.068469   
...       ...                     ...                        ...   
17628  186676                0.039969                   0.044873   
17629  186676                0.052578                   0.057127   
17630  186676                0.091189                   0.044224   
17631  186676                0.378373                   0.132694   
17632  186676                0.033435                   0.031001   

       Polygon Area(gyrozx)  Polygon Perimeter(gyrozx)  
0                  0.003716                   0.138271  
1                  0.025011                   0.075452  
2           

In [38]:
print(gyroxy_features.columns)
print(gyroyz_features.columns)
print(gyrozx_features.columns)


Index(['ID', 'Ferret Measure(gyroxy)', 'Centroid Distance(gyroxy)',
       'Polygon Area(gyroxy)', 'Polygon Perimeter(gyroxy)'],
      dtype='object')
Index(['ID', 'Ferret Measure(gyroyz)', 'Centroid Distance(gyroyz)',
       'Polygon Area(gyroyz)', 'Polygon Perimeter(gyroyz)'],
      dtype='object')
Index(['ID', 'Ferret Measure(gyrozx)', 'Centroid Distance(gyrozx)',
       'Polygon Area(gyrozx)', 'Polygon Perimeter(gyrozx)'],
      dtype='object')


In [39]:
import pandas as pd

# Replace 'gyroxy_features', 'gyroyz_features', 'gyrozx_features' with your actual dataframe variables
gyroxy_features = gyroxy_features# your dataframe
gyroyz_features = gyroyz_features# your dataframe
gyrozx_features = gyrozx_features# your dataframe

# Check the column names and adjust if necessary
print(gyroxy_features.columns)
print(gyroyz_features.columns)
print(gyrozx_features.columns)

# Assuming the ID column is named correctly and exists in your dataframes
# Extract the 'ID' column from one dataframe and set it aside
id_column = gyroxy_features[['ID']]  # Replace 'ID' with the actual column name if it's different

# Drop the 'ID' column from the other dataframes to avoid duplication
gyroxy_features.drop(columns=['ID'], inplace=True)
gyroyz_features.drop(columns=['ID'], inplace=True)
gyrozx_features.drop(columns=['ID'], inplace=True)

# Concatenate the dataframes horizontally
Gyro_all_df = pd.concat([id_column, gyroxy_features, gyroyz_features, gyrozx_features], axis=1)

print(Gyro_all_df)



Index(['ID', 'Ferret Measure(gyroxy)', 'Centroid Distance(gyroxy)',
       'Polygon Area(gyroxy)', 'Polygon Perimeter(gyroxy)'],
      dtype='object')
Index(['ID', 'Ferret Measure(gyroyz)', 'Centroid Distance(gyroyz)',
       'Polygon Area(gyroyz)', 'Polygon Perimeter(gyroyz)'],
      dtype='object')
Index(['ID', 'Ferret Measure(gyrozx)', 'Centroid Distance(gyrozx)',
       'Polygon Area(gyrozx)', 'Polygon Perimeter(gyrozx)'],
      dtype='object')
           ID  Ferret Measure(gyroxy)  Centroid Distance(gyroxy)  \
0      100669                0.616612                   0.157566   
1      100669                1.580424                   0.178812   
2      100669                0.950282                   0.150707   
3      100669                0.903312                   0.386830   
4      100669                0.570392                   0.240423   
...       ...                     ...                        ...   
17628  186676                1.003663                   0.126849   
176

In [40]:
import pandas as pd

# Replace 'gyroxy_features', 'gyroyz_features', 'gyrozx_features' with your actual dataframe variables
acceleroxy_features = acceleroxy_features# your dataframe
acceleroyz_features = acceleroyz_features# your dataframe
accelerozx_features = accelerozx_features# your dataframe

# Check the column names and adjust if necessary
print(acceleroxy_features.columns)
print(acceleroyz_features.columns)
print(accelerozx_features.columns)

# Assuming the ID column is named correctly and exists in your dataframes
# Extract the 'ID' column from one dataframe and set it aside
id_column = acceleroxy_features[['ID']]  # Replace 'ID' with the actual column name if it's different

# Drop the 'ID' column from the other dataframes to avoid duplication
acceleroxy_features.drop(columns=['ID'], inplace=True)
acceleroyz_features.drop(columns=['ID'], inplace=True)
accelerozx_features.drop(columns=['ID'], inplace=True)

# Concatenate the dataframes horizontally
Accelero_all_df = pd.concat([id_column, acceleroxy_features, acceleroyz_features, accelerozx_features], axis=1)

print(Accelero_all_df)

Index(['ID', 'Ferret Measure(accxy)', 'Centroid Distance(accxy)',
       'Polygon Area(accxy)', 'Polygon Perimeter(accxy)'],
      dtype='object')
Index(['ID', 'Ferret Measure(accyz)', 'Centroid Distance(accyz)',
       'Polygon Area(accyz)', 'Polygon Perimeter(accyz)'],
      dtype='object')
Index(['ID', 'Ferret Measure(acczx)', 'Centroid Distance(acczx)',
       'Polygon Area(acczx)', 'Polygon Perimeter(acczx)'],
      dtype='object')
           ID  Ferret Measure(accxy)  Centroid Distance(accxy)  \
0      100669               0.653896                  0.307439   
1      100669               1.046059                  0.356021   
2      100669               1.561073                  0.288214   
3      100669               0.985135                  4.509599   
4      100669               1.534549                  0.371832   
...       ...                    ...                       ...   
17630  186676               1.094025                  0.142493   
17631  186676               0.8

In [41]:
Accelero_all_df = Accelero_all_df[:-2]

In [42]:
print(Accelero_all_df)

           ID  Ferret Measure(accxy)  Centroid Distance(accxy)  \
0      100669               0.653896                  0.307439   
1      100669               1.046059                  0.356021   
2      100669               1.561073                  0.288214   
3      100669               0.985135                  4.509599   
4      100669               1.534549                  0.371832   
...       ...                    ...                       ...   
17628  186676               1.183922                  0.158304   
17629  186676               0.973371                  0.154844   
17630  186676               1.094025                  0.142493   
17631  186676               0.869119                  0.146733   
17632  186676               0.942703                  0.115567   

       Polygon Area(accxy)  Polygon Perimeter(accxy)  Ferret Measure(accyz)  \
0                 0.126997                 10.049717               0.740989   
1                 0.396814                 11.305

In [43]:
import pandas as pd

# Replace 'gyroxy_features', 'gyroyz_features', 'gyrozx_features' with your actual dataframe variables
Accelero_all_df = Accelero_all_df
Gyro_all_df = Gyro_all_df


# Assuming the ID column is named correctly and exists in your dataframes
# Extract the 'ID' column from one dataframe and set it aside
id_column = Accelero_all_df[['ID']]  # Replace 'ID' with the actual column name if it's different

# Drop the 'ID' column from the other dataframes to avoid duplication
Accelero_all_df.drop(columns=['ID'], inplace=True)
Gyro_all_df.drop(columns=['ID'], inplace=True)

# Concatenate the dataframes horizontally
All_df = pd.concat([id_column, Accelero_all_df,Gyro_all_df], axis=1)

print(All_df)

           ID  Ferret Measure(accxy)  Centroid Distance(accxy)  \
0      100669               0.653896                  0.307439   
1      100669               1.046059                  0.356021   
2      100669               1.561073                  0.288214   
3      100669               0.985135                  4.509599   
4      100669               1.534549                  0.371832   
...       ...                    ...                       ...   
17628  186676               1.183922                  0.158304   
17629  186676               0.973371                  0.154844   
17630  186676               1.094025                  0.142493   
17631  186676               0.869119                  0.146733   
17632  186676               0.942703                  0.115567   

       Polygon Area(accxy)  Polygon Perimeter(accxy)  Ferret Measure(accyz)  \
0                 0.126997                 10.049717               0.740989   
1                 0.396814                 11.305

In [44]:
pip install pandas scikit-learn numpy

DEPRECATION: pyodbc 4.0.0-unsupported has a non-standard version number. pip 24.0 will enforce this behaviour change. A possible replacement is to upgrade to a newer version of pyodbc or contact the author to suggest that they release a version with a conforming version number. Discussion can be found at https://github.com/pypa/pip/issues/12063


# KNN ALGORITHM


In [45]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score

# Assuming 'All_df' is your DataFrame
X = All_df.drop('ID', axis=1)  # Features
y = All_df['ID']  # Labels

kf = KFold(n_splits=25, shuffle=True, random_state=42)

knn_accuracies = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize KNN, fit on training data, and make predictions
    knn = KNeighborsClassifier(n_neighbors=10)  # You can change the number of neighbors
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)

    # Calculate accuracy and append to list
    accuracy = accuracy_score(y_test, predictions)
    knn_accuracies.append(accuracy)

# Calculate average accuracy across all folds
average_accuracy = sum(knn_accuracies) / len(knn_accuracies)
print(f'Average KNN Accuracy: {average_accuracy}')


Average KNN Accuracy: 0.6355648243023326


In [46]:
from sklearn.model_selection import KFold
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import accuracy_score, confusion_matrix
import numpy as np

# Assuming 'All_df' is your DataFrame
X = All_df.drop('ID', axis=1)  # Features
y = All_df['ID']  # Labels

kf = KFold(n_splits=40, shuffle=True, random_state=42)

knn_accuracies = []
conf_matrices = []

for train_index, test_index in kf.split(X):
    X_train, X_test = X.iloc[train_index], X.iloc[test_index]
    y_train, y_test = y.iloc[train_index], y.iloc[test_index]

    # Initialize KNN, fit on training data, and make predictions
    knn = KNeighborsClassifier(n_neighbors=15)  # You can change the number of neighbors
    knn.fit(X_train, y_train)
    predictions = knn.predict(X_test)

    # Calculate accuracy and append to list
    accuracy = accuracy_score(y_test, predictions)
    knn_accuracies.append(accuracy)

    # Calculate and store the confusion matrix
    conf_matrix = confusion_matrix(y_test, predictions)
    conf_matrices.append(conf_matrix)

# Calculate average accuracy across all folds
average_accuracy = sum(knn_accuracies) / len(knn_accuracies)
print(f'Average KNN Accuracy: {average_accuracy}')

# Sum the confusion matrices from each fold to get a combined confusion matrix
combined_conf_matrix = np.sum(conf_matrices, axis=0)
print('Combined Confusion Matrix:')
print(combined_conf_matrix)


Average KNN Accuracy: 0.6389710884353741
Combined Confusion Matrix:
[[3375  422  198  192  142]
 [ 758 2139  316  141  205]
 [ 279  218 2578  196  119]
 [ 551  356  518  956  182]
 [ 548  492  296  237 2219]]


In [47]:
from sklearn.model_selection import train_test_split


X = All_df.drop('ID', axis=1)  
y = All_df['ID'] 

X_trainf, X_testf, y_trainf, y_testf = train_test_split(X, y, test_size=0.25, random_state=42)

In [48]:
from sklearn.neighbors import KNeighborsClassifier


knn = KNeighborsClassifier(n_neighbors=15)


knn.fit(X_trainf, y_trainf)


y_pred1 = knn.predict(X_testf)


accuracy = knn.score(X_testf, y_testf)


print("Accuracy:", accuracy)

Accuracy: 0.6364254933091404


In [49]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import GridSearchCV, KFold
from sklearn.metrics import confusion_matrix

knn_classifier = KNeighborsClassifier()
my_param_grid = {'n_neighbors': [15, 20, 30], 'leaf_size': [20, 30, 40]}
my_cv = KFold(n_splits=10, shuffle=True)  

knn_model_gs = GridSearchCV(estimator=knn_classifier, 
                            param_grid=my_param_grid,
                            cv=my_cv,
                            scoring='accuracy')

knn_model_gs.fit(X_trainf, y_trainf)

best_knn_model = knn_model_gs.best_estimator_

best_knn_model.fit(X_trainf, y_trainf)

y_predkf = best_knn_model.predict(X_testf)


cm = confusion_matrix(y_testf, y_predkf)


print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[837  99  55  49  33]
 [182 523  83  37  52]
 [ 83  61 665  50  25]
 [142  87 141 228  43]
 [130 132  55  52 565]]


In [50]:
knn_model_gs.fit(X_trainf, y_trainf)

GridSearchCV(cv=KFold(n_splits=10, random_state=None, shuffle=True),
             estimator=KNeighborsClassifier(),
             param_grid={'leaf_size': [20, 30, 40],
                         'n_neighbors': [15, 20, 30]},
             scoring='accuracy')

In [51]:

knn_best_classifier = knn_model_gs.best_estimator_


In [52]:
print(knn_model_gs.best_params_)

{'leaf_size': 20, 'n_neighbors': 20}


In [53]:
knn_model_gs.cv_results_

{'mean_fit_time': array([0.02145357, 0.02440646, 0.02151513, 0.02070372, 0.0211602 ,
        0.02456741, 0.02042081, 0.02119401, 0.02097957]),
 'std_fit_time': array([0.00713751, 0.00755337, 0.00557623, 0.00725615, 0.00706291,
        0.00839085, 0.00725061, 0.00719197, 0.00711322]),
 'mean_score_time': array([0.07792828, 0.07171443, 0.07732227, 0.06712437, 0.07297125,
        0.07107942, 0.07688308, 0.07133312, 0.07311623]),
 'std_score_time': array([0.0071136 , 0.00737623, 0.00447196, 0.00693667, 0.0070594 ,
        0.01094499, 0.00847027, 0.01124362, 0.00699796]),
 'param_leaf_size': masked_array(data=[20, 20, 20, 30, 30, 30, 40, 40, 40],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill_value='?',
             dtype=object),
 'param_n_neighbors': masked_array(data=[15, 20, 30, 15, 20, 30, 15, 20, 30],
              mask=[False, False, False, False, False, False, False, False,
                    False],
        fill

In [54]:
knn_best_classifier.get_params()

{'algorithm': 'auto',
 'leaf_size': 20,
 'metric': 'minkowski',
 'metric_params': None,
 'n_jobs': None,
 'n_neighbors': 20,
 'p': 2,
 'weights': 'uniform'}

In [55]:
from sklearn.model_selection import cross_val_score
scores = cross_val_score(knn_best_classifier, X_trainf, y_trainf, cv=my_cv, scoring='accuracy')
list(scores)

[0.6409674981103552,
 0.6137566137566137,
 0.6258503401360545,
 0.6341647770219199,
 0.6346444780635401,
 0.6225416036308623,
 0.6036308623298033,
 0.6452344931921331,
 0.6384266263237519,
 0.624054462934947]

In [56]:
y_train_predkf=knn_best_classifier.predict(X_trainf)

In [57]:
accuracy_score(y_true=y_trainf, y_pred=y_train_predkf)

0.6608439201451906

In [58]:
y_test_predkf = knn_best_classifier.predict(X_testf)

In [59]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_testf, y_test_predkf)


print("Confusion Matrix:")
print(cm)


Confusion Matrix:
[[837  99  55  49  33]
 [182 523  83  37  52]
 [ 83  61 665  50  25]
 [142  87 141 228  43]
 [130 132  55  52 565]]


In [60]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV

svm_classifier = SVC()

param_grid = {'C': [0.1, 1, 10], 'kernel': ['linear', 'rbf'], 'gamma': [0.1, 1, 10]}

grid_search = GridSearchCV(estimator=svm_classifier, param_grid=param_grid, cv=5, scoring='accuracy')
grid_search.fit(X_trainf, y_trainf)

best_svm_classifier = grid_search.best_estimator_

best_svm_classifier.fit(X_trainf, y_trainf)

y_predf = best_svm_classifier.predict(X_testf)


In [61]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_testf, y_predf)

print("Accuracy:", accuracy)

Accuracy: 0.7375822181900658
